<?php

use Illuminate\Database\Seeder;
use App\Model\Soorah as MSoorah;

class Soorah extends Seeder
{
    public function run()
    {
        MSoorah::create(['id' => 1, 'name' => 'Al-Faatihah', 'order' => 1]);
        MSoorah::create(['id' => 2, 'name' => 'Al-Baqarah', 'order' => 2]);
        MSoorah::create(['id' => 3, 'name' => "Ali 'Imran", 'order' => 3]);
        MSoorah::create(['id' => 4, 'name' => "An-Nisaa'", 'order' => 4]);
        MSoorah::create(['id' => 5, 'name' => "Al-Maa'idah", 'order' => 5]);
        MSoorah::create(['id' => 6, 'name' => "Al-An'am", 'order' => 6]);
        MSoorah::create(['id' => 7, 'name' => "Al-A’raf", 'order' => 7]);
        MSoorah::create(['id' => 8, 'name' => "Al-Anfal", 'order' => 8]);
        MSoorah::create(['id' => 9, 'name' => "At-Taubah", 'order' => 9]);
        MSoorah::create(['id' => 10, 'name' => "Yunus", 'order' => 10]);
        MSoorah::create(['id' => 11, 'name' => "Hud", 'order' => 11]);
        MSoorah::create(['id' => 12, 'name' => "Yusuf", 'order' => 12]);
        MSoorah::create(['id' => 13, 'name' => "Ar-Ra’d", 'order' => 13]);
        MSoorah::create(['id' => 14, 'name' => "Ibrahim", 'order' => 14]);
        MSoorah::create(['id' => 15, 'name' => "Al-Hijr", 'order' => 15]);
        MSoorah::create(['id' => 16, 'name' => "An-Nahl", 'order' => 16]);
        MSoorah::create(['id' => 17, 'name' => "Al-Israa’", 'order' => 17]);
        MSoorah::create(['id' => 18, 'name' => "Al-Kahf", 'order' => 18]);
        MSoorah::create(['id' => 19, 'name' => "Maryam", 'order' => 19]);
        MSoorah::create(['id' => 20, 'name' => "Taa Haa", 'order' => 20]);
        MSoorah::create(['id' => 21, 'name' => "Al-Anbiyaa'", 'order' => 21]);
        MSoorah::create(['id' => 22, 'name' => "Al-Hajj", 'order' => 22]);
        MSoorah::create(['id' => 23, 'name' => "Al-Mu’minuun", 'order' => 23]);
        MSoorah::create(['id' => 24, 'name' => "An-Nuur", 'order' => 24]);
        MSoorah::create(['id' => 25, 'name' => "Al-Furqaan", 'order' => 25]);
        MSoorah::create(['id' => 26, 'name' => "Asy-Syu’araa’ ", 'order' => 26]);
        MSoorah::create(['id' => 27, 'name' => "An-Naml", 'order' => 27]);
        MSoorah::create(['id' => 28, 'name' => "Al-Qashash", 'order' => 28]);
        MSoorah::create(['id' => 29, 'name' => "Al-‘Ankabuut", 'order' => 29]);
        MSoorah::create(['id' => 30, 'name' => "Ar-Ruum", 'order' => 30]);
        MSoorah::create(['id' => 31, 'name' => "Luqmaan", 'order' => 31]);
        MSoorah::create(['id' => 32, 'name' => "As-Sajdah", 'order' => 32]);
        MSoorah::create(['id' => 33, 'name' => "Al-Ahzaab", 'order' => 33]);
        MSoorah::create(['id' => 34, 'name' => "Sabaa’ ", 'order' => 34]);
        MSoorah::create(['id' => 35, 'name' => "Faathir ", 'order' => 35]);
        MSoorah::create(['id' => 36, 'name' => "Ya Sin", 'order' => 36]);
        MSoorah::create(['id' => 37, 'name' => "Ash-Shaaffat", 'order' => 37]);
        MSoorah::create(['id' => 38, 'name' => "Sad", 'order' => 38]);
        MSoorah::create(['id' => 39, 'name' => "Az-Zumar ", 'order' => 39]);
        MSoorah::create(['id' => 40, 'name' => "Al-Mu’min", 'order' => 40]);
        MSoorah::create(['id' => 41, 'name' => "Fussilat", 'order' => 41]);
        MSoorah::create(['id' => 42, 'name' => "Asy-Syuura", 'order' => 42]);
        MSoorah::create(['id' => 43, 'name' => "Az-Zukhruf", 'order' => 43]);
        MSoorah::create(['id' => 44, 'name' => "Ad-Dukhaan", 'order' => 44]);
        MSoorah::create(['id' => 45, 'name' => "Al-Jaatsiyah", 'order' => 45]);
        MSoorah::create(['id' => 46, 'name' => "Al-Ahqaaf", 'order' => 46]);
        MSoorah::create(['id' => 47, 'name' => "Muhammad ", 'order' => 47]);
        MSoorah::create(['id' => 48, 'name' => "Al-Fath", 'order' => 48]);
        MSoorah::create(['id' => 49, 'name' => "Al-Hujuraat", 'order' => 49]);
        MSoorah::create(['id' => 50, 'name' => "Qaf", 'order' => 50]);
        MSoorah::create(['id' => 51, 'name' => "Adz-Dzaariyaat", 'order' => 51]);
        MSoorah::create(['id' => 52, 'name' => "Ath-Thuur", 'order' => 52]);
        MSoorah::create(['id' => 53, 'name' => "An-Najm", 'order' => 53]);
        MSoorah::create(['id' => 54, 'name' => "Al-Qamar", 'order' => 54]);
        MSoorah::create(['id' => 55, 'name' => "Ar-Rahman", 'order' => 55]);
        MSoorah::create(['id' => 56, 'name' => "Al-Waaqi’ah", 'order' => 56]);
        MSoorah::create(['id' => 57, 'name' => "Al-Hadiid", 'order' => 57]);
        MSoorah::create(['id' => 58, 'name' => "Al-Mujaadilah", 'order' => 58]);
        MSoorah::create(['id' => 59, 'name' => "Al-Hasyr", 'order' => 59]);
        MSoorah::create(['id' => 60, 'name' => "Al-Mumtahanah", 'order' => 60]);
        MSoorah::create(['id' => 61, 'name' => "Ash-Shaff ", 'order' => 61]);
        MSoorah::create(['id' => 62, 'name' => "Al-Jumu’ah", 'order' => 62]);
        MSoorah::create(['id' => 63, 'name' => "Al-Munaafiquun", 'order' => 63]);
        MSoorah::create(['id' => 64, 'name' => "At-Taghaabun", 'order' => 64]);
        MSoorah::create(['id' => 65, 'name' => "Ath-Thalaaq", 'order' => 65]);
        MSoorah::create(['id' => 66, 'name' => "At-Tahriim", 'order' => 66]);
        MSoorah::create(['id' => 67, 'name' => "Al-Mulk", 'order' => 67]);
        MSoorah::create(['id' => 68, 'name' => "Al-Qalam", 'order' => 68]);
        MSoorah::create(['id' => 69, 'name' => "Al-Haaqqah", 'order' => 69]);
        MSoorah::create(['id' => 70, 'name' => "Al-Ma’arij", 'order' => 70]);
        MSoorah::create(['id' => 71, 'name' => "Nuh", 'order' => 71]);
        MSoorah::create(['id' => 72, 'name' => "Al-Jinn", 'order' => 72]);
        MSoorah::create(['id' => 73, 'name' => "Al-Muzzammil", 'order' => 73]);
        MSoorah::create(['id' => 74, 'name' => "Al-Muddatstsir", 'order' => 74]);
        MSoorah::create(['id' => 75, 'name' => "Al-Qiyamah", 'order' => 75]);
        MSoorah::create(['id' => 76, 'name' => "Al-Insan", 'order' => 76]);
        MSoorah::create(['id' => 77, 'name' => "Al-Mursalat", 'order' => 77]);
        MSoorah::create(['id' => 78, 'name' => "An-Naba’", 'order' => 78]);
        MSoorah::create(['id' => 79, 'name' => "An-Nazi’at", 'order' => 79]);
        MSoorah::create(['id' => 80, 'name' => "‘Abasa", 'order' => 80]);
        MSoorah::create(['id' => 81, 'name' => "At-Takwir", 'order' => 81]);
        MSoorah::create(['id' => 82, 'name' => "Al-Infitar", 'order' => 82]);
        MSoorah::create(['id' => 83, 'name' => "Al-Muthaffifin", 'order' => 83]);
        MSoorah::create(['id' => 84, 'name' => "Al-Insyiqaq", 'order' => 84]);
        MSoorah::create(['id' => 85, 'name' => "Al-Buruj", 'order' => 85]);
        MSoorah::create(['id' => 86, 'name' => "At-Tariq", 'order' => 86]);
        MSoorah::create(['id' => 87, 'name' => "Al-A’la", 'order' => 87]);
        MSoorah::create(['id' => 88, 'name' => "Al-Ghaasyiyah", 'order' => 88]);
        MSoorah::create(['id' => 89, 'name' => "Al-Fajr", 'order' => 89]);
        MSoorah::create(['id' => 90, 'name' => "Al-Balad", 'order' => 90]);
        MSoorah::create(['id' => 91, 'name' => "Asy-Syams", 'order' => 91]);
        MSoorah::create(['id' => 92, 'name' => "Al-Lail", 'order' => 92]);
        MSoorah::create(['id' => 93, 'name' => "Ad-Duhaa", 'order' => 93]);
        MSoorah::create(['id' => 94, 'name' => "Al-Insyirah", 'order' => 94]);
        MSoorah::create(['id' => 95, 'name' => "At-Tiin", 'order' => 95]);
        MSoorah::create(['id' => 96, 'name' => "Al-‘Alaq", 'order' => 96]);
        MSoorah::create(['id' => 97, 'name' => "Al-Qadr", 'order' => 97]);
        MSoorah::create(['id' => 98, 'name' => "Al-Bayyinah", 'order' => 98]);
        MSoorah::create(['id' => 99, 'name' => "Az-Zalzalah", 'order' => 99]);
        MSoorah::create(['id' => 100, 'name' => "Al-‘Aadiyat", 'order' => 100]);
        MSoorah::create(['id' => 101, 'name' => "Al-Qaari’ah", 'order' => 101]);
        MSoorah::create(['id' => 102, 'name' => "At-Takatsur ", 'order' => 102]);
        MSoorah::create(['id' => 103, 'name' => "Al-‘Asr", 'order' => 103]);
        MSoorah::create(['id' => 104, 'name' => "Al-Humazah", 'order' => 104]);
        MSoorah::create(['id' => 105, 'name' => "Al-Fiil", 'order' => 105]);
        MSoorah::create(['id' => 106, 'name' => "Quraisy", 'order' => 106]);
        MSoorah::create(['id' => 107, 'name' => "Al-Maa’uun", 'order' => 107]);
        MSoorah::create(['id' => 108, 'name' => "Al-Kautsar", 'order' => 108]);
        MSoorah::create(['id' => 109, 'name' => "Al-Kaafiruun", 'order' => 109]);
        MSoorah::create(['id' => 110, 'name' => "An-Nasr", 'order' => 110]);
        MSoorah::create(['id' => 111, 'name' => "Al-Lahab", 'order' => 111]);
        MSoorah::create(['id' => 112, 'name' => "Al-Ikhlas", 'order' => 112]);
        MSoorah::create(['id' => 113, 'name' => "Al-Falaq", 'order' => 113]);
        MSoorah::create(['id' => 114, 'name' => "An-Naas", 'order' => 114]);

    }
}